name: youtube-check

on:
  schedule:
    - cron: '00 01,13 * * *' # runs every day at 1am and 1pm

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.8' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client==2.60.0 discord==2.0.0
          
      - name: execute py script # run script to grab data and post it on Discord
        env: 
          YOUTUBE_SECRET: ${{ secrets.YOUTUBE_SECRET }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        run: python youtube_check_discord_result.py Dashpong
      
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "update streams list" -a
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master  
